### PR TITLE
fix minor comment typo

### PR DESCRIPTION
**Pull request by morya**
they break godoc

### CODE REVIEW

**Comment by brett19** [comment]
Hey @morya,

Would you be able to quickly sign our CLA so I can accept this directly from you?

Cheers, Brett

**Comment by morya** [comment]
@brett19 I have signed CLA.

**Comment by ingenthr** [comment]
@morya it looks like you didn't add your email and it wasn't picked up automatically from your identity provider.  can you add the same email to your profile at http://review.couchbase.org/#/settings/ ?  That's where it seems to be stuck.

Sorry for the hassle-- I'm sure you understand we need to do it correctly!

**Comment by morya** [comment]
I admire the attitude.
It should be ok now.

**Comment by ingenthr** [comment]
And the bot picked it up just fine!  Thanks for that @morya .

**Pull request closed without merging**
