### PR TITLE
fix SetRemove when removing last item

### PR DESCRIPTION
**Pull request by ishmulyan**
SetRemove writes null into the document when removing last item from set.

### CODE REVIEW

**Comment by ishmulyan** [comment]
@brett19 reason?

**Comment by brett19** [comment]
Hey @ishmulyan ,
This ended up being corrected by the following changeset:
https://github.com/couchbase/gocb/commit/b25045addd5e483a935737b2e9e12fdf8f216949
Cheers, Brett

**Comment by brett19** [comment]
In hindsight, that is a different issue.  Sorry about that.

**Comment by ishmulyan** [comment]
Hey @brett19,
Do you know when release with the fix is going to be?

**Comment by avsej** [comment]
@ishmulyan according to git, this commit has been released in 1.3.3: https://github.com/couchbase/gocb/commit/b25045addd5e483a935737b2e9e12fdf8f216949

**Comment by ishmulyan** [comment]
@avsej, that was another issue.

**Pull request closed without merging**
