### PR TITLE
Dont url encode json marshaled values

### PR DESCRIPTION
**Pull request by buchanan**

### CODE REVIEW

**Comment by brett19** [comment]
While this is technically correct, the method to avoid url encoding marshalled values is only available in more recent Go versions and would break support with older versions, which must be completed in at least a minor (major?) version change.

**Comment by voutasaurus** [comment]
> While this is technically correct, the method to avoid url encoding marshalled values is only available in more recent Go versions and would break support with older versions, which must be completed in at least a minor (major?) version change.

Go has build tags to target specific Go versions, using them does not require a minor or major version change of gocb.

Also where is the documentation on which Go versions are currently supported for this package?

**Comment by brett19** [comment]
Hey @buchanan,
@chvck recently mentioned that we actually have already switched to using Go 1.7 features, and thus this should be merged soon!  Thanks for rebasing it to the latest.
Cheers, Brett

**Comment by brett19** [comment]
Looks like the commit is failing our formatting check though.  Would you be willing to update the commit with the fixed formatting?

**Pull request closed without merging**
