### PR TITLE
Update gopkg.in link in README now that v1 is tagged

### PR DESCRIPTION
**Pull request by borgstrom**

### CODE REVIEW

**Comment by brett19** [comment]
Thanks for the pull request!!  To ensure quality review, Couchbase employs a [code review system](http://review.couchbase.org/) based on [Gerrit](https://www.gerritcodereview.com/) to manage the workflow of changes in addition to tracking our contributor agreements.

To get this change in and collaborate in code review, please register on Gerrit and accept our CLA.  More detailed instructions are available here: https://developer.couchbase.com/open-source-projects#how-to-contribute-code.

Note: Please contact us if you have any issues registering with Gerrit!  If you are not registered after 7 days, the Pull Request will automatically be closed.

::SDKBOT/PR:no_cla

**Comment by borgstrom** [comment]
Definitely not going to sing a CLA for a 1 byte change.

Hopefully you can make the update yourself...

**Comment by brett19** [comment]
Automated Bot.  Apologizes.

**Comment by brett19** [comment]
Change available here: http://review.couchbase.org/55674

**Comment by borgstrom** [comment]
All good.  Thanks, @brett19

**Pull request closed without merging**
