### PR TITLE
adding createIndexWhere

### PR DESCRIPTION
**Pull request by borosr**
Try to fix this issue: https://issues.couchbase.com/browse/GOCBC-651

### CODE REVIEW

**Comment by borosr** [comment]
Hi @chvck. Yes, what should I do next?

**Comment by chvck** [comment]
Hi @borosr our gerrit code review system doesn't seem to think that you've signed our CLA. Does the email in the commit and the email that you've used to sign up with match?

**Comment by borosr** [comment]
Now I checked it out, just missed email setup. Yes, they are match.

**Comment by brett19** [comment]
This has been fixed in the 2.x release.

**Pull request closed without merging**
