### PR TITLE
Fix CounterOp (allow counter init value to 0)

### PR DESCRIPTION
**Pull request by dragos-oancea**

### CODE REVIEW

**Comment by dragos-oancea** [comment]
The docs say: "Counter performs an atomic addition or subtraction for an integer document. Passing a non-negative `initial` value will cause the document to be created if it did not already exist." . 
Zero is a non-negative value.

**Comment by brett19** [comment]
Hey @dragos-oancea ,
Unfortunately, this is a documentation issue and not a code issue.  Keep in mind that in the case of the Counter operations, the `initial` value is value placed into the document directly, and 0 is not a supported case for this.

The logic is more or less as follows:
```
if !document.exists {
  document.value = amount
} else {
  document.value += delta
}
```

Cheers, Brett

**Comment by dragos-oancea** [comment]
Hi @brett19 ,

Thanks for looking into this. . 
All I want is a Counter with a value of 0 when I initialize it.
This does not work unless I apply the change in this PR:
items = append(items, &couchbase.CounterOp{Key: foo + ":bar:counter", Delta: 1, Initial: 0, Expiry: m.C.Couchbase.Expiry})
In my case the document does not exist.

And I cannot do CounterOp with Delta:0 , it throws an error

**Comment by brett19** [comment]
Hey @dragos-oancea,
Unfortunately, changing this behaviour would break the majority of applications who are relying on the concept of 0 being the 'disable-value'.  Perhaps an alternative solution would be to execute an .Insert op with a value of 0 just prior to performing the counter in cases where the document may not yet exist?
Cheers, Brett

**Comment by dragos-oancea** [comment]
thanks @brett19  for the suggestion, it worked.

**Pull request closed without merging**
