### PR TITLE
GetBytes method added to QueryResults Similar to Next

### PR DESCRIPTION
**Pull request by sh0umik**
GetBytes Method is Same as Next but it maps to []byte instead of interface{} . It is needed in my micro-service where I am pulling document through protobuffer . The JSON is complicated and large So I had to marshal the struct again into bytes since i can not send interface{} through protobuffer . In order to send over gRPC with protobuffer i needed only the Bytes array. Then for each query I saved extra marshal and unmarshal overhead . Since Next method already unmarshal into struct/interface{}. It helps a lot in the performance.

### CODE REVIEW

**Comment by brett19** [comment]
Hey @sh0umik,
The GetBytes() method that already exists should be sufficient for this use case?  It will return a byte-slice of the data (before unmarshalling).  This is the same data passed into the marshalling for Next().
Cheers, Brett

**Comment by sh0umik** [comment]
@brett19 Correct me if I am wrong , The only method Exists for QueryResults is `NetBytes()` . I wasn't able to run it with For loop  like `Next()`
```
for rows.NextBytes() {
}
```
The only way I made `NextBytes()` to work is by knowing the length of the rows . How to get that ? 
The `GetBytes()` acts like Next instead It skips the 
```
r.err = json.Unmarshal(row, valuePtr)
```
and returns only the Bytes :) . Anyway I am using it in my Fork , thought it might be useful where user wants the raw bytes array out of the DB without unmarshaling .

**Comment by brett19** [comment]
Hey @sh0umik,

Wouldn't this work in for looping over the results and receiving the bytes?
```go
for rowBytes := rows.NextBytes() {
  // Do something with rowBytes here...
}
```

**Comment by sh0umik** [comment]
@brett19 

```
for rowBytes := rows.NextBytes() {
  // Do something with rowBytes here...
}
```
Gives Syntax error as `syntax error: rowBytes := rows.NextBytes() used as value`

I am using it like this 

```
	matrix := rows.Metrics()

	for i := 0; i <= int(matrix.ResultCount); i++ {
		res = append(rows.NextBytes(), res...)
		fmt.Println(string(rows.NextBytes()))
	}
```

**Comment by brett19** [comment]
Hey @sh0umik,
Sorry, your right.  Doesn't look like Go allows you to perform the kind of loop I had originally suggested.  I imagine this would work though:
```go
for rowBytes := rows.NextBytes(); rowBytes != nil; rowBytes = rows.NextBytes() {
	// ...
}
```

**Pull request closed without merging**
