### PR TITLE
Fix goroutine leaking when using durability

### PR DESCRIPTION
**Pull request by sysecho**
When using durability, the number of goroutines is always increasing.
The function _observeOne_ is blocking, trying to send a message to either _replicaCh_ or _persistCh_, but the function _durability_ is not reading from these channels anymore once it reached the target durability settings.
Thus, _numServers_ goroutines are blocked on writes and never return.

There is a special case, If we ask for maximum replica and persist durability, the function will enter a endless loop, polling the server every 100ms.

By using buffered channels we ensure the writes are not blocking anymore, and once _replicaCh_ and _persistCh_ have been written, we can exit the goroutine.

### CODE REVIEW

**Comment by sysecho** [comment]
I signed the CLA.

**Comment by brett19** [comment]
Hey @sysecho,

It's likely that the email you signed the commit with is not attached to your Gerrit profile, which would cause the bot not to be able to detect it.

Cheers, Brett

**Comment by sysecho** [comment]
Hey @brett19,

You're right, this is a different email address.
I tried to register this one in Gerrit 10 minutes ago but I'm not receiving Gerrit's email confirmation.

**Comment by sysecho** [comment]
Well, Gerrit can't seem to be able to send the confirmation to my secondary email (checked spams as well).
Tried with other domains, it works.

**Comment by brett19** [comment]
Hey @sysecho,
Let me look into this for you.
Cheers, Brett

**Comment by brett19** [comment]
Hey @sysecho,
I cannot find any reason why your secondary email refuses to receive any confirmation email.  Are you certain that email routing and DNS is configured properly for that address?
Cheers, Brett

**Comment by sysecho** [comment]
Hey @brett19,
The email address is provided by an internet provider in France and I'm receiving emails all the day at this here.
By the way, all the emails received from Gerrit at my other address are marked as spam ( sent from northscale.com with couchbase.org domain but no dkim, no spf, ... ); maybe my provider has too strict rules against this.
Should I commit my changes again with my primary Gerrit's email and re-open a merge request ?

**Comment by brett19** [comment]
Hey @sysecho,
That would work.  I'm going to look into getting the DKIM and SPF records corrected for that server.
Cheers, Brett

**Pull request closed without merging**
