### PR TITLE
On InsertBucket error the function should return error instead nil

### PR DESCRIPTION
**Pull request by ch3lo**
InsertBucket should return err instead nil.

### CODE REVIEW

**Comment by brett19** [comment]
Hey,
Any chance you would be able to sign the CLA so we can merge this directly?
Cheers, Brett

**Comment by brett19** [comment]
Hey,
I'd really like you to get the credit for this catch.  Any chance you can sign the CLA?
Cheers, Brett

**Comment by ch3lo** [comment]
Hi, I signed the cla when i did the PR.


Regards

**Comment by brett19** [comment]
http://review.couchbase.org/#/c/77559/

**Pull request closed without merging**
