### PR TITLE
Update go commands to new url

### PR DESCRIPTION
**Pull request by SonarBeserk**
@brett19
The README.md lists the go command to get the older version of the lib.

### CODE REVIEW

**Comment by brett19** [comment]
Hey,
Any chance you would be able to sign the CLA so we can merge this directly?
Cheers, Brett

**Comment by SonarBeserk** [comment]
@brett19 I actually already signed the CLA

**Comment by brett19** [comment]
@SonarBeserk , would you be willing to login to gerrit and add your github email so there we can link that CLA back to your commit?

Thanks! Brett

**Comment by SonarBeserk** [comment]
@brett19 It should be fixed now

**Comment by brett19** [comment]
Hmm.  The bot seems to be disagreeing.  You've added this email `son*****erk@gma***com` (as above) to your Gerrit account (and the CLA is signed on that account)?

**Comment by SonarBeserk** [comment]
I have yes.

**Pull request closed without merging**
